#!/bin/bash
# This input is normally used as the argument to sbatch job submission with slurm
# requires:
# - DEFAULT_ACCOUNT defined or -A argument given to sbatch
# - ADC_PREFIX defined pointing to an adc installation
#SBATCH --partition=short,batch
#SBATCH --time=00:02:00
#SBATCH --account=$DEFAULT_ACCOUNT
#SBATCH -N 2
#SBATCH -n 4
#SBATCH --licenses=gpfs
#SBATCH --output %j-%t-%s.out 

. local-install-list
#check the cmake with mpi build
export OMPI_MCA_smsc="^knem"
mpirun -N 2 -n 4 $ADC_PREFIX/bin/mpi.simple.demo
##srun --output %j-%t-%s.out -N 2 -n 4 $ADC_PREFIX/bin/mpi.simple.demo
