#!/bin/bash
# This input is normally used as the argument to sbatch job submission with slurm
# requires:
# - DEFAULT_ACCOUNT defined or -A argument given to sbatch
# - ADC_PREFIX defined pointing to an adc installation
#SBATCH --partition=short,batch
#SBATCH --time=00:02:00
#SBATCH --account=$DEFAULT_ACCOUNT
#SBATCH -N 2
#SBATCH -n 4

. local-install-list
#check the cmake with mpi build
srun --output %j-%t-%s.out -N 2 -n 4 $ADC_PREFIX/bin/mpi.simple.demo
