name: doxygen build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Doxygen setup
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen
        run: |
          doxygen doc/Doxyfile

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: doc/doxygen/html

# deploy:
#   needs: build
#   runs-on: ubuntu-latest
#   environment:
#     name: github-pages
#     url: ${{ steps.deployment.outputs.page_url }}
#   steps:
#     - name: Deploy to GitHub Pages Preview
#       id: deployment
#       uses: actions/deploy-pages@v3


#
#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: doc/doxygen/html
#         publish_branch: doc-deploy
